class ConfigInit:
    url = 'https://bacon.lpi-china.com'
    sendaddr_name = '1171499448@qq.com'
    sendaddr_pswd = 'expfsnlwjyecjddj'
    data_filename = 'login.xls'
    mongo_user = 'name'
    mongo_pw = 'pw'
    mongo_ip = 'ip'
    AccessKey = 'key'
    SecretKey = 'key'
    qiniu_domain = 'domain'
    qiniu_house = 'house'
